### ISSUE TITLE
installation error, any idea?

### ISSUE THREAD

**Issue by mnbe1973** [AMLab-Amsterdam/lie_learn#33]
Collecting git+https://github.com/AMLab-Amsterdam/lie_learn
  Cloning https://github.com/AMLab-Amsterdam/lie_learn to c:\users\owner\appdata\local\temp\pip-req-build-hk264gwd
  Running command git clone --filter=blob:none --quiet https://github.com/AMLab-Amsterdam/lie_learn 'C:\Users\Owner\AppData\Local\Temp\pip-req-build-hk264gwd'
  Resolved https://github.com/AMLab-Amsterdam/lie_learn to commit 1ccc2106e402d517a29de5438c9367c959e67338
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      warning: lie_learn\groups\SO3.pyx:100:8: Unreachable code

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      #Jb = np.load(os.path.join(os.path.dirname(__file__), 'J_block_0-478.npy'), allow_pickle=True)

      FLOAT_TYPE = np.float64
      ctypedef np.float64_t FLOAT_TYPE_t
      INT_TYPE = np.int
      ctypedef np.int_t INT_TYPE_t
               ^
      ------------------------------------------------------------

      lie_learn\representations\SO3\pinchon_hoggan\pinchon_hoggan.pyx:25:9: 'int_t' is not a type identifier
      Compiling lie_learn\groups\SO3.pyx because it changed.
      Compiling lie_learn\representations\SO3\irrep_bases.pyx because it changed.
      Compiling lie_learn\representations\SO3\pinchon_hoggan\pinchon_hoggan.pyx because it changed.
      Compiling lie_learn\spaces\spherical_quadrature.pyx because it changed.
      [1/4] Cythonizing lie_learn\groups\SO3.pyx
      [2/4] Cythonizing lie_learn\representations\SO3\irrep_bases.pyx
      [3/4] Cythonizing lie_learn\representations\SO3\pinchon_hoggan\pinchon_hoggan.pyx
      Traceback (most recent call last):
        File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Owner\AppData\Local\Temp\pip-build-env-2clc9zwe\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Owner\AppData\Local\Temp\pip-build-env-2clc9zwe\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\Owner\AppData\Local\Temp\pip-build-env-2clc9zwe\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\Owner\AppData\Local\Temp\pip-build-env-2clc9zwe\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\Owner\AppData\Local\Temp\pip-build-env-2clc9zwe\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: lie_learn\representations\SO3\pinchon_hoggan\pinchon_hoggan.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mnbe1973** [comment]
Hi again,
reading all there is about this problem I managed to get it to work using python 3.8 and the following lib. ver. 

# requirements.txt

autograd==1.6.2
certifi==2024.7.4
charset-normalizer==3.3.2
Cython==0.29.21
escnn==1.0.11
filelock==3.15.4
fsspec==2024.6.1
future==1.0.0
idna==3.7
intel-openmp==2021.4.0
jinja2==3.1.4
joblib==1.4.2
lie-learn==0.0.1.post1
MarkupSafe==2.1.5
mkl==2021.4.0
mpmath==1.3.0
networkx==3.1
numpy==1.24.4
py3nj==0.2.1
pymanopt==2.2.0
requests==2.32.3
scipy==1.9.3
sympy==1.13.1
tbb==2021.13.0
torch==2.3.1
typing-extensions==4.12.2
urllib3==2.2.2

/M
